"""Tests for scripts/cost_table.py (the dry-mode table generator)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.cost_table import (  # noqa: E402
    DEFAULT_TFVARS_PATH,
    ENGINES,
    SCALE_TIERS,
    TierSizing,
    build_rows,
    load_throughput_qps,
    main,
    parse_terraform_tiers,
    render_markdown,
)
from vector_bench.cost import InfraSpec, cost_per_query  # noqa: E402
from vector_bench.prices import aws_us_east_1_snapshot  # noqa: E402

# ----- Terraform parser --------------------------------------------------


SAMPLE_TF = """\
locals {
  tiers = {
    "1m" = {
      instance_type    = "m6i.large" # 2 vCPU, 8 GiB
      data_volume_gb   = 50
      iops             = 3000
      throughput_mibps = 125
    }
    "10m" = {
      instance_type    = "r6i.xlarge"
      data_volume_gb   = 200
      iops             = 6000
      throughput_mibps = 250
    }
    "100m" = {
      instance_type    = "r6i.4xlarge"
      data_volume_gb   = 1500
      iops             = 12000
      throughput_mibps = 500
    }
  }
}
"""


def test_parse_terraform_tiers_extracts_all_three_tiers():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    assert set(tiers) == set(SCALE_TIERS)
    assert tiers["1m"] == TierSizing(
        scale_tier="1m",
        instance_type="m6i.large",
        data_volume_gb=50,
        provisioned_iops=3000,
        provisioned_throughput_mibps=125,
    )
    assert tiers["10m"].instance_type == "r6i.xlarge"
    assert tiers["100m"].provisioned_iops == 12000


def test_parse_terraform_tiers_tolerates_inline_comments():
    """The Terraform locals carry `# vCPU + memory` comments."""
    tiers = parse_terraform_tiers(SAMPLE_TF)
    assert tiers["1m"].instance_type == "m6i.large"


def test_parse_terraform_tiers_raises_when_block_incomplete():
    bad = SAMPLE_TF.replace("iops             = 3000\n", "")
    with pytest.raises(ValueError, match="missing one or more required fields"):
        parse_terraform_tiers(bad)


def test_parse_terraform_tiers_raises_when_tier_block_missing():
    # Drop the 100m block.
    truncated = SAMPLE_TF.split('"100m"')[0] + "\n  }\n}\n"
    with pytest.raises(ValueError, match="missing tier blocks"):
        parse_terraform_tiers(truncated)


def test_parse_terraform_tiers_works_against_committed_main_tf():
    """Source-of-truth invariant: the committed Terraform file must
    parse against this module's parser, otherwise the cost table can't
    be regenerated by CI."""
    text = DEFAULT_TFVARS_PATH.read_text(encoding="utf-8")
    tiers = parse_terraform_tiers(text)
    assert set(tiers) == set(SCALE_TIERS)
    # Light sanity: 100m should have a larger volume than 1m.
    assert tiers["100m"].data_volume_gb > tiers["1m"].data_volume_gb
    assert tiers["100m"].provisioned_iops >= tiers["10m"].provisioned_iops


# ----- Throughput loader -------------------------------------------------


def test_load_throughput_qps_reads_c001_json(tmp_path: Path):
    run_dir = tmp_path / "load" / "stub-10k"
    run_dir.mkdir(parents=True)
    (run_dir / "c001.json").write_text(json.dumps({"throughput_qps": 1234.5}))
    assert load_throughput_qps(run_dir) == pytest.approx(1234.5)


def test_load_throughput_qps_raises_when_c001_missing(tmp_path: Path):
    run_dir = tmp_path / "load" / "no-such-run"
    run_dir.mkdir(parents=True)
    with pytest.raises(FileNotFoundError, match="c001.json"):
        load_throughput_qps(run_dir)


# ----- build_rows --------------------------------------------------------


def test_build_rows_produces_one_row_per_tier_engine_combination():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {"1m": 1000.0, "10m": 800.0, "100m": 400.0}
    prices = aws_us_east_1_snapshot()
    rows = build_rows(tiers, qps_by_tier, prices)
    assert len(rows) == len(SCALE_TIERS) * len(ENGINES)
    seen = {(r.scale_tier, r.engine) for r in rows}
    expected = {(t, e) for t in SCALE_TIERS for e in ENGINES}
    assert seen == expected


def test_build_rows_same_tier_same_cost_across_engines():
    """The Terraform locals share instance + EBS across engines per
    tier; the monthly cost should match exactly between (1m, pgvector)
    and (1m, qdrant)."""
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {t: 1000.0 for t in SCALE_TIERS}
    rows = build_rows(tiers, qps_by_tier, aws_us_east_1_snapshot())
    by_tier: dict[str, list[float]] = {}
    for r in rows:
        by_tier.setdefault(r.scale_tier, []).append(r.monthly_cost.total_usd_month)
    for tier_name, totals in by_tier.items():
        assert len(set(totals)) == 1, (
            f"tier {tier_name} has differing monthly cost across engines: {totals}"
        )


def test_build_rows_propagates_qps_per_tier():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {"1m": 100.0, "10m": 200.0, "100m": 300.0}
    rows = build_rows(tiers, qps_by_tier, aws_us_east_1_snapshot())
    for r in rows:
        assert r.throughput_qps == qps_by_tier[r.scale_tier]


# ----- render_markdown ---------------------------------------------------


def test_render_markdown_includes_every_row_and_assumptions_block():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {t: 1000.0 for t in SCALE_TIERS}
    prices = aws_us_east_1_snapshot()
    rows = build_rows(tiers, qps_by_tier, prices)
    md = render_markdown(
        rows,
        prices=prices,
        qps_source={t: "results/load/stub-10k/c001.json" for t in SCALE_TIERS},
    )
    assert "# Cost per query" in md
    assert "## Assumptions" in md
    assert "## Per-tier table" in md
    assert "What the numbers say" in md
    assert prices.snapshot_date in md
    assert "730" in md  # hours per month
    assert "2,628,000" in md  # seconds per month
    for tier in SCALE_TIERS:
        assert f"| {tier} |" in md, f"tier row {tier} missing from table"
    for engine in ENGINES:
        assert f"| {engine} |" in md, f"engine row {engine} missing from table"


def test_render_markdown_quotes_the_source_url():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {t: 1000.0 for t in SCALE_TIERS}
    prices = aws_us_east_1_snapshot()
    md = render_markdown(
        build_rows(tiers, qps_by_tier, prices),
        prices=prices,
        qps_source={t: "anything" for t in SCALE_TIERS},
    )
    assert prices.source_url in md


# ----- main() ------------------------------------------------------------


def test_main_runs_dry_and_writes_committed_artifact(tmp_path: Path):
    """End-to-end: --dry mode reads the committed Terraform file +
    committed results, writes a markdown table to `out`, exits 0.
    Verifies the script works against the real repo layout, not a
    fixture."""
    out_path = tmp_path / "docs" / "cost_per_query.md"
    rc = main(["--dry", "--out", str(out_path)])
    assert rc == 0
    assert out_path.exists()
    text = out_path.read_text(encoding="utf-8")
    assert "Cost per query" in text
    # The committed stub-10k results' throughput is ~1623 qps; both
    # the engine rows and the tier rows should show up.
    for engine in ENGINES:
        assert engine in text
    for tier in SCALE_TIERS:
        assert f"| {tier} |" in text


def test_main_dry_reproduces_known_monthly_costs(tmp_path: Path):
    """Belt-and-braces: the committed Terraform tiers + the committed
    pricing snapshot yield specific monthly costs. If any of those
    files moves, this test surfaces the drift."""
    out_path = tmp_path / "out.md"
    main(["--dry", "--out", str(out_path)])

    tiers = parse_terraform_tiers(DEFAULT_TFVARS_PATH.read_text(encoding="utf-8"))
    prices = aws_us_east_1_snapshot()
    expected_totals: dict[str, float] = {}
    for tier_name in SCALE_TIERS:
        spec = InfraSpec(
            scale_tier=tier_name,
            engine="pgvector",
            instance_type=tiers[tier_name].instance_type,
            data_volume_gb=tiers[tier_name].data_volume_gb,
            provisioned_iops=tiers[tier_name].provisioned_iops,
            provisioned_throughput_mibps=tiers[tier_name].provisioned_throughput_mibps,
        )
        cpq = cost_per_query(spec, prices, 1000.0)
        expected_totals[tier_name] = cpq.monthly_cost.total_usd_month
    text = out_path.read_text(encoding="utf-8")
    # Every tier's monthly cost should appear in the rendered text.
    for tier_name, total in expected_totals.items():
        assert f"${total:.2f}" in text, (
            f"expected monthly {total:.2f} for tier {tier_name} in the markdown, got:\n{text[:500]}"
        )
