"""Tests for scripts/cost_table.py (the dry-mode table generator)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.cost_table import (  # noqa: E402
    DEFAULT_TFVARS_PATH,
    ENGINES,
    SCALE_TIERS,
    TierSizing,
    build_rows,
    load_throughput_qps,
    main,
    parse_terraform_tiers,
    render_markdown,
)
from vector_bench.cost import InfraSpec, cost_per_query  # noqa: E402
from vector_bench.prices import aws_us_east_1_snapshot  # noqa: E402

# ----- Terraform parser --------------------------------------------------


SAMPLE_TF = """\
locals {
  tiers = {
    "1m" = {
      instance_type    = "m6i.large" # 2 vCPU, 8 GiB
      data_volume_gb   = 50
      iops             = 3000
      throughput_mibps = 125
    }
    "10m" = {
      instance_type    = "r6i.xlarge"
      data_volume_gb   = 200
      iops             = 6000
      throughput_mibps = 250
    }
    "100m" = {
      instance_type    = "r6i.4xlarge"
      data_volume_gb   = 1500
      iops             = 12000
      throughput_mibps = 500
    }
  }
}
"""


def test_parse_terraform_tiers_extracts_all_three_tiers():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    assert set(tiers) == set(SCALE_TIERS)
    assert tiers["1m"] == TierSizing(
        scale_tier="1m",
        instance_type="m6i.large",
        data_volume_gb=50,
        provisioned_iops=3000,
        provisioned_throughput_mibps=125,
    )
    assert tiers["10m"].instance_type == "r6i.xlarge"
    assert tiers["100m"].provisioned_iops == 12000


def test_parse_terraform_tiers_tolerates_inline_comments():
    """The Terraform locals carry `# vCPU + memory` comments."""
    tiers = parse_terraform_tiers(SAMPLE_TF)
    assert tiers["1m"].instance_type == "m6i.large"


def test_parse_terraform_tiers_raises_when_block_incomplete():
    bad = SAMPLE_TF.replace("iops             = 3000\n", "")
    with pytest.raises(ValueError, match="missing one or more required fields"):
        parse_terraform_tiers(bad)


def test_parse_terraform_tiers_raises_when_tier_block_missing():
    # Drop the 100m block.
    truncated = SAMPLE_TF.split('"100m"')[0] + "\n  }\n}\n"
    with pytest.raises(ValueError, match="missing tier blocks"):
        parse_terraform_tiers(truncated)


def test_parse_terraform_tiers_works_against_committed_main_tf():
    """Source-of-truth invariant: the committed Terraform file must
    parse against this module's parser, otherwise the cost table can't
    be regenerated by CI."""
    text = DEFAULT_TFVARS_PATH.read_text(encoding="utf-8")
    tiers = parse_terraform_tiers(text)
    assert set(tiers) == set(SCALE_TIERS)
    # Light sanity: 100m should have a larger volume than 1m.
    assert tiers["100m"].data_volume_gb > tiers["1m"].data_volume_gb
    assert tiers["100m"].provisioned_iops >= tiers["10m"].provisioned_iops


# ----- Throughput loader -------------------------------------------------


def test_load_throughput_qps_reads_c001_json(tmp_path: Path):
    run_dir = tmp_path / "load" / "stub-10k"
    run_dir.mkdir(parents=True)
    (run_dir / "c001.json").write_text(json.dumps({"throughput_qps": 1234.5}))
    assert load_throughput_qps(run_dir) == pytest.approx(1234.5)


def test_load_throughput_qps_raises_when_c001_missing(tmp_path: Path):
    run_dir = tmp_path / "load" / "no-such-run"
    run_dir.mkdir(parents=True)
    with pytest.raises(FileNotFoundError, match="c001.json"):
        load_throughput_qps(run_dir)


@pytest.mark.parametrize("bad", [True, False])
def test_load_throughput_qps_rejects_boolean(tmp_path: Path, bad: bool):
    # bool subclasses int, so `float(True)` is 1.0 — a JSON `true` in a
    # hand-edited c001.json would amortize the cost table over a fabricated 1.0
    # qps. Reject it (ValueError -> main's exit-2 handler), the sibling of the
    # plot_latency._load_matrix boolean guard.
    run_dir = tmp_path / "load" / "stub-10k"
    run_dir.mkdir(parents=True)
    (run_dir / "c001.json").write_text(json.dumps({"throughput_qps": bad}))
    with pytest.raises(ValueError, match="throughput_qps must be a number"):
        load_throughput_qps(run_dir)


# ----- build_rows --------------------------------------------------------


def test_build_rows_produces_one_row_per_tier_engine_combination():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {"1m": 1000.0, "10m": 800.0, "100m": 400.0}
    prices = aws_us_east_1_snapshot()
    rows = build_rows(tiers, qps_by_tier, prices)
    assert len(rows) == len(SCALE_TIERS) * len(ENGINES)
    seen = {(r.scale_tier, r.engine) for r in rows}
    expected = {(t, e) for t in SCALE_TIERS for e in ENGINES}
    assert seen == expected


def test_build_rows_same_tier_same_cost_across_engines():
    """The Terraform locals share instance + EBS across engines per
    tier; the monthly cost should match exactly between (1m, pgvector)
    and (1m, qdrant)."""
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {t: 1000.0 for t in SCALE_TIERS}
    rows = build_rows(tiers, qps_by_tier, aws_us_east_1_snapshot())
    by_tier: dict[str, list[float]] = {}
    for r in rows:
        by_tier.setdefault(r.scale_tier, []).append(r.monthly_cost.total_usd_month)
    for tier_name, totals in by_tier.items():
        assert len(set(totals)) == 1, (
            f"tier {tier_name} has differing monthly cost across engines: {totals}"
        )


def test_build_rows_propagates_qps_per_tier():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {"1m": 100.0, "10m": 200.0, "100m": 300.0}
    rows = build_rows(tiers, qps_by_tier, aws_us_east_1_snapshot())
    for r in rows:
        assert r.throughput_qps == qps_by_tier[r.scale_tier]


# ----- render_markdown ---------------------------------------------------


def test_render_markdown_includes_every_row_and_assumptions_block():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {t: 1000.0 for t in SCALE_TIERS}
    prices = aws_us_east_1_snapshot()
    rows = build_rows(tiers, qps_by_tier, prices)
    md = render_markdown(
        rows,
        prices=prices,
        qps_source={t: "results/load/stub-10k/c001.json" for t in SCALE_TIERS},
    )
    assert "# Cost per query" in md
    assert "## Assumptions" in md
    assert "## Per-tier table" in md
    assert "What the numbers say" in md
    assert prices.snapshot_date in md
    assert "730" in md  # hours per month
    assert "2,628,000" in md  # seconds per month
    for tier in SCALE_TIERS:
        assert f"| {tier} |" in md, f"tier row {tier} missing from table"
    for engine in ENGINES:
        assert f"| {engine} |" in md, f"engine row {engine} missing from table"


def test_render_markdown_quotes_the_source_url():
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {t: 1000.0 for t in SCALE_TIERS}
    prices = aws_us_east_1_snapshot()
    md = render_markdown(
        build_rows(tiers, qps_by_tier, prices),
        prices=prices,
        qps_source={t: "anything" for t in SCALE_TIERS},
    )
    assert prices.source_url in md


def test_render_markdown_escapes_pipe_in_throughput_source_so_columns_dont_break():
    # The five shipped tiers/engines keep the table pipe-free, but the
    # throughput-source cell carries the operator-supplied `--load-results
    # TIER=PATH` directory, and a pipe in that path lands in a GFM cell. A raw
    # `|` (even inside a code span) splits the cell and adds a spurious column,
    # corrupting the whole table's alignment. Assert the piped data row's
    # unescaped-pipe count equals the header's — i.e. the source cell
    # contributes zero extra delimiters. Fails pre-fix (the piped row carried
    # one more unescaped pipe than the header). See issue #76.
    tiers = parse_terraform_tiers(SAMPLE_TF)
    qps_by_tier = {t: 1000.0 for t in SCALE_TIERS}
    prices = aws_us_east_1_snapshot()
    rows = build_rows(tiers, qps_by_tier, prices)
    piped = "`/tmp/a|b/c001.json` (real)"
    md = render_markdown(
        rows,
        prices=prices,
        qps_source={t: piped for t in SCALE_TIERS},
    )
    lines = md.splitlines()
    header_line = next(line for line in lines if line.startswith("| Scale |"))
    row_line = next(line for line in lines if line.startswith("| 1m |"))

    def unescaped_pipes(s: str) -> int:
        # A `\|` renders as a literal pipe and does NOT split the cell; only a
        # bare `|` is a column delimiter. Count pipes not preceded by a backslash.
        return sum(1 for i, ch in enumerate(s) if ch == "|" and (i == 0 or s[i - 1] != "\\"))

    assert unescaped_pipes(row_line) == unescaped_pipes(header_line)
    # The literal pipe is preserved (escaped), not dropped.
    assert "a\\|b" in row_line


# ----- main() ------------------------------------------------------------


def test_main_runs_dry_and_writes_committed_artifact(tmp_path: Path):
    """End-to-end: --dry mode reads the committed Terraform file +
    committed results, writes a markdown table to `out`, exits 0.
    Verifies the script works against the real repo layout, not a
    fixture."""
    out_path = tmp_path / "docs" / "cost_per_query.md"
    rc = main(["--dry", "--out", str(out_path)])
    assert rc == 0
    assert out_path.exists()
    text = out_path.read_text(encoding="utf-8")
    assert "Cost per query" in text
    # The committed stub-10k results' throughput is ~1623 qps; both
    # the engine rows and the tier rows should show up.
    for engine in ENGINES:
        assert engine in text
    for tier in SCALE_TIERS:
        assert f"| {tier} |" in text


def test_main_dry_reproduces_known_monthly_costs(tmp_path: Path):
    """Belt-and-braces: the committed Terraform tiers + the committed
    pricing snapshot yield specific monthly costs. If any of those
    files moves, this test surfaces the drift."""
    out_path = tmp_path / "out.md"
    main(["--dry", "--out", str(out_path)])

    tiers = parse_terraform_tiers(DEFAULT_TFVARS_PATH.read_text(encoding="utf-8"))
    prices = aws_us_east_1_snapshot()
    expected_totals: dict[str, float] = {}
    for tier_name in SCALE_TIERS:
        spec = InfraSpec(
            scale_tier=tier_name,
            engine="pgvector",
            instance_type=tiers[tier_name].instance_type,
            data_volume_gb=tiers[tier_name].data_volume_gb,
            provisioned_iops=tiers[tier_name].provisioned_iops,
            provisioned_throughput_mibps=tiers[tier_name].provisioned_throughput_mibps,
        )
        cpq = cost_per_query(spec, prices, 1000.0)
        expected_totals[tier_name] = cpq.monthly_cost.total_usd_month
    text = out_path.read_text(encoding="utf-8")
    # Every tier's monthly cost should appear in the rendered text.
    for tier_name, total in expected_totals.items():
        assert f"${total:.2f}" in text, (
            f"expected monthly {total:.2f} for tier {tier_name} in the markdown, got:\n{text[:500]}"
        )


# ----- --dry/--no-dry labeling + --load-results per-tier overrides (#25) -----


def _seed_load_results_dir(dest: Path, qps: float) -> Path:
    """Write a minimal c001.json with the given throughput_qps so a
    --load-results override has something to read."""
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "c001.json").write_text(
        json.dumps({"throughput_qps": qps, "p95_latency_ms": 1.0}),
        encoding="utf-8",
    )
    return dest


def _table_row_lines(md: str) -> list[str]:
    """Extract the per-tier table rows from the rendered markdown.

    Lets the labeling tests below check the row-level Throughput source
    column without false positives from the explanatory prose paragraph
    that mentions `(simulated)` as documentation."""
    return [
        line
        for line in md.splitlines()
        if line.startswith("| ")
        and "stub-10k" in line
        or (line.startswith("| ") and "real_1m_run" in line)
    ]


def test_main_default_dry_labels_every_row_simulated(tmp_path: Path):
    out_path = tmp_path / "out.md"
    rc = main(["--out", str(out_path)])
    assert rc == 0
    rows = _table_row_lines(out_path.read_text(encoding="utf-8"))
    assert rows, "expected per-tier table rows in the markdown"
    for row in rows:
        assert "(simulated)" in row, f"row missing (simulated) marker under default --dry: {row}"
        assert "(real)" not in row


def test_main_no_dry_drops_simulated_marker_from_rows(tmp_path: Path):
    out_path = tmp_path / "out.md"
    rc = main(["--no-dry", "--out", str(out_path)])
    assert rc == 0
    rows = _table_row_lines(out_path.read_text(encoding="utf-8"))
    assert rows, "expected per-tier table rows in the markdown"
    for row in rows:
        assert "(simulated)" not in row, (
            f"row should not carry (simulated) under --no-dry without override: {row}"
        )
        assert "(real)" not in row


def test_main_load_results_override_labels_tier_real(tmp_path: Path):
    override_dir = _seed_load_results_dir(tmp_path / "real_1m_run", qps=2500.0)
    out_path = tmp_path / "out.md"
    rc = main(
        [
            "--out",
            str(out_path),
            "--load-results",
            f"1m={override_dir}",
        ]
    )
    assert rc == 0
    rows = _table_row_lines(out_path.read_text(encoding="utf-8"))
    real_rows = [r for r in rows if "real_1m_run" in r]
    other_rows = [r for r in rows if "real_1m_run" not in r]
    assert real_rows, "expected at least one row pointing at the override dir"
    for row in real_rows:
        assert "(real)" in row, f"override-rule row missing (real) marker: {row}"
    for row in other_rows:
        assert "(simulated)" in row, (
            f"non-overridden row should remain (simulated) under default --dry: {row}"
        )


def test_main_load_results_unknown_tier_exits_2_and_lists_known(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
):
    rc = main(
        [
            "--out",
            str(tmp_path / "out.md"),
            "--load-results",
            f"made-up-tier={tmp_path}",
        ]
    )
    captured = capsys.readouterr()
    assert rc == 2
    assert "unknown tier" in captured.err
    for known in SCALE_TIERS:
        assert known in captured.err
    assert not (tmp_path / "out.md").exists()


def test_main_load_results_malformed_entry_exits_2(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
):
    rc = main(
        [
            "--out",
            str(tmp_path / "out.md"),
            "--load-results",
            "no-equals-sign-here",
        ]
    )
    captured = capsys.readouterr()
    assert rc == 2
    assert "expected TIER=PATH" in captured.err


# ----- missing-input files translate to exit 2 (exit-code contract #85) -----


def test_main_missing_tf_main_exits_2_not_traceback(tmp_path: Path, capsys):
    # A missing operator-supplied --tf-main must translate to a clean exit 2
    # (like the sibling plot_latency.py #85 / the _parse_load_results_overrides
    # guard), not escape as a raw FileNotFoundError traceback.
    missing = tmp_path / "no_such_main.tf"
    rc = main(["--dry", "--tf-main", str(missing), "--out", str(tmp_path / "out.md")])
    assert rc == 2
    assert str(missing) in capsys.readouterr().err


def test_main_non_utf8_tf_main_exits_2_not_traceback(tmp_path: Path, capsys):
    # A present-but-non-UTF-8 --tf-main is unreadable input, the same class as
    # the missing-file case: read_text(encoding="utf-8") raises UnicodeDecodeError
    # (a ValueError subclass, NOT a FileNotFoundError), which escaped the guard
    # and leaked a raw traceback at exit 1. It must translate to a clean exit 2
    # (sibling of llm-eval-harness#174 / prompt-regression-suite#126).
    bad = tmp_path / "bad_main.tf"
    bad.write_bytes(b"\xff\xfe\x00not utf-8")
    rc = main(["--dry", "--tf-main", str(bad), "--out", str(tmp_path / "out.md")])
    assert rc == 2
    assert "not valid UTF-8" in capsys.readouterr().err


def test_main_unwritable_out_exits_2_not_traceback(tmp_path: Path, capsys):
    # The output path is operator input too: an unwritable --out must land as a
    # clean exit 2, not a raw OSError traceback (write-seam sibling of the input
    # guards above and llm-eval-harness#158/#159). A path whose parent component
    # is a FILE makes atomic_write_text's mkdir raise NotADirectoryError (an
    # OSError) — a deterministic, portable unwritable target.
    blocker = tmp_path / "blocker"
    blocker.write_text("x")
    out_path = blocker / "sub" / "cost.md"
    rc = main(["--dry", "--out", str(out_path)])
    assert rc == 2
    err = capsys.readouterr().err
    assert "could not write" in err
    assert "Traceback" not in err


def test_main_malformed_c001_json_exits_2_not_traceback(tmp_path: Path, capsys):
    # A c001.json supplied via --load-results is operator input; a present-but-
    # malformed (valid-UTF-8-but-not-valid-JSON) one raises json.JSONDecodeError
    # from load_throughput_qps, which — like the plot scripts' matrix/grid reads
    # in this same change — must translate to a clean exit 2, not leak a raw
    # traceback at exit 1.
    results_dir = tmp_path / "load"
    results_dir.mkdir()
    (results_dir / "c001.json").write_text("{not valid json", encoding="utf-8")
    rc = main(["--dry", "--load-results", f"1m={results_dir}", "--out", str(tmp_path / "out.md")])
    assert rc == 2
    assert "not valid JSON" in capsys.readouterr().err


def test_main_missing_results_dir_exits_2_with_operator_message(tmp_path: Path, capsys):
    # A missing load-harness c001.json must surface load_throughput_qps's
    # operator-facing "Re-run the load harness" message on stderr with exit 2,
    # instead of burying it in a traceback.
    rc = main(["--run-id", "no-such-run", "--out", str(tmp_path / "out.md")])
    assert rc == 2
    err = capsys.readouterr().err
    assert "Re-run the load harness" in err


# ----- the value axis of the exit-code contract (#115) -----------------------
#
# `main`'s input-load block caught FileNotFoundError / UnicodeDecodeError /
# json.JSONDecodeError only, while the guards *inside* it deliberately raise
# ValueError (bool qps, non-numeric string, zero/NaN/Infinity qps via
# cost_per_query, terraform tier problems), TypeError (null / non-object
# payload) and KeyError (absent field). Every one escaped as a raw traceback at
# exit 1, so those guards were raising into nothing — `load_throughput_qps`'s
# own comment even claimed `main` translated them. `plot_latency.main` has had
# the `(TypeError, ValueError, KeyError)` arm all along; these lock the parity.
#
# Each case asserts exit 2 AND the absence of a traceback: the exit code alone
# can't distinguish "handled cleanly" from "handled, then dumped a stack anyway".


def _write_c001(tmp_path: Path, body: str) -> Path:
    results_dir = tmp_path / "load"
    results_dir.mkdir(exist_ok=True)
    (results_dir / "c001.json").write_text(body, encoding="utf-8")
    return results_dir


@pytest.mark.parametrize(
    ("body", "needle"),
    [
        # ValueError from load_throughput_qps's own bool guard — the one whose
        # comment asserted it reached an exit-2 handler that did not exist.
        ('{"throughput_qps": true}', "not a bool"),
        # ValueError from float() on a non-numeric string.
        ('{"throughput_qps": "abc"}', "could not convert string to float"),
        # TypeError from float(None).
        ('{"throughput_qps": null}', "float()"),
        # KeyError from the absent required field.
        ('{"qps": 5}', "throughput_qps"),
        # TypeError from subscripting a non-object payload.
        ("[1, 2]", "list indices"),
    ],
)
def test_main_structurally_invalid_c001_exits_2_naming_the_file(
    tmp_path: Path, capsys, body: str, needle: str
):
    results_dir = _write_c001(tmp_path, body)
    rc = main(["--dry", "--load-results", f"1m={results_dir}", "--out", str(tmp_path / "out.md")])
    assert rc == 2
    err = capsys.readouterr().err
    assert "Traceback" not in err
    # The message names *which* input was bad — `main` reads the terraform file
    # and one c001.json per tier, so an undifferentiated message is unactionable.
    assert str(results_dir) in err
    assert needle in err


@pytest.mark.parametrize("qps_literal", ["0", "NaN", "Infinity"])
def test_main_unusable_qps_exits_2_rather_than_fabricating_a_row(
    tmp_path: Path, capsys, qps_literal: str
):
    # These pass float() cleanly and are only rejected one layer down by
    # `cost_per_query`, which fires *after* the load block. An Infinity qps would
    # otherwise amortize to a fabricated $0.00/query row (handoff §10), and the
    # refusal that prevents that has to reach the operator as exit 2. `NaN` and
    # `Infinity` are bare tokens `json.loads` parses natively, so no Python is
    # needed to produce such a c001.json.
    results_dir = _write_c001(tmp_path, f'{{"throughput_qps": {qps_literal}}}')
    out_path = tmp_path / "out.md"
    rc = main(["--dry", "--load-results", f"1m={results_dir}", "--out", str(out_path)])
    assert rc == 2
    err = capsys.readouterr().err
    assert "Traceback" not in err
    assert "positive and finite" in err
    # Nothing was published: the refusal happens before the write seam.
    assert not out_path.exists()


@pytest.mark.parametrize(
    ("tf_body", "needle"),
    [
        # No tier blocks at all.
        ('variable "x" {}\n', "missing tier blocks"),
        # A tier block present but missing required fields.
        ('"1m" = { instance_type = "m5.large" }\n"10m" = {}\n"100m" = {}\n', "missing one or more"),
    ],
)
def test_main_invalid_tf_main_exits_2_naming_the_file(
    tmp_path: Path, capsys, tf_body: str, needle: str
):
    # `--tf-main` is documented operator input. A file that reads and decodes but
    # doesn't parse as tier sizing raises ValueError out of parse_terraform_tiers,
    # which had no arm — the terraform-side sibling of the c001.json cases above.
    tf = tmp_path / "main.tf"
    tf.write_text(tf_body, encoding="utf-8")
    rc = main(["--dry", "--tf-main", str(tf), "--out", str(tmp_path / "out.md")])
    assert rc == 2
    err = capsys.readouterr().err
    assert "Traceback" not in err
    assert str(tf) in err
    assert needle in err


def test_main_happy_path_still_exits_0_and_writes(tmp_path: Path):
    # The new arm must not swallow a working run. Guards that only ever fire are
    # indistinguishable from guards that always fire without this.
    results_dir = _write_c001(tmp_path, '{"throughput_qps": 5}')
    out_path = tmp_path / "out.md"
    rc = main(["--dry", "--load-results", f"1m={results_dir}", "--out", str(out_path)])
    assert rc == 0
    assert out_path.exists()
    assert "| Scale | Engine |" in out_path.read_text(encoding="utf-8")


def test_cost_table_matches_plot_latency_value_axis_catch_shape():
    """`cost_table.main` and `plot_latency.main` must agree on which exception
    types are bad operator input, or the two published artifacts disagree on
    what a malformed results file means. Derived from the sources rather than
    restated, so a future divergence in either file fails here."""
    import ast

    def value_axis_arms(path: Path) -> set[str]:
        tree = ast.parse(path.read_text(encoding="utf-8"))
        found: set[str] = set()
        for node in ast.walk(tree):
            if not isinstance(node, ast.ExceptHandler) or node.type is None:
                continue
            names = node.type.elts if isinstance(node.type, ast.Tuple) else [node.type]
            caught = {n.id for n in names if isinstance(n, ast.Name)}
            if {"TypeError", "ValueError", "KeyError"} & caught:
                found |= caught
        return found

    scripts_dir = _REPO_ROOT / "scripts"
    assert {"TypeError", "ValueError", "KeyError"} <= value_axis_arms(scripts_dir / "cost_table.py")
    assert {"TypeError", "ValueError", "KeyError"} <= value_axis_arms(
        scripts_dir / "plot_latency.py"
    )
